global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # Get blackbox_exporter metrics
  - job_name: blackbox
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:9115

  # ICMP probes
  #
  # Get metrics about targets
  - job_name: blackbox_ping_simple
    metrics_path: /probe
    params:
      module: [icmp]
      target: [8.8.8.8]
    static_configs:
      - targets:
        - localhost:9115

  # Get metrics about targets using 'relabel_configs'
  - job_name: blackbox_ping_relabel
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8 # There will be placed __address__
    relabel_configs:
      # Set target for prober from 'targets'
      - source_labels: [__address__]
        target_label: __param_target
      # Save target address to metric's label 'instance'
      - source_labels: [__address__]
        target_label: instance
      # Save module name to metric
      - source_labels: [__param_module]
        target_label: module
      # Place blackbox_exporter's URL at target's place
      - target_label: __address__
        replacement: localhost:9115

  # TCP probes
  #
  # Test TCP connection using 'relabel_configs'
  - job_name: blackbox_tcp_connect_relabel
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - host.docker.internal:22
    relabel_configs:
      # Set target for prober from 'targets'
      - source_labels: [__address__]
        target_label: __param_target
      # Save target from 'targets' to label 'instance'
      - source_labels: [__address__]
        target_label: instance
      # Save module name to label 'module'
      - source_labels: [__param_module]
        target_label: module
      # Place blackbox_exporter's URL at target's place
      - target_label: __address__
        replacement: localhost:9115
